### ISSUE TITLE
Client id length validation

### ISSUE THREAD

**Issue by mrdg** [surge/surgemq#4]
Hi,

I was wondering why the length check [here](https://github.com/surge/surgemq/blob/master/message/connect.go#L625) limits the client id to max 23 bytes. 

The 3.1.1 spec says you must allow client id's with a length between 1 and 23, but it doesn't say you can't have client id's longer than 23 bytes right? Or am I misunderstanding?

**Comment by zhenjl** [comment]
@mrdg you are correct. The spec says "The Server MAY allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above." 

I took the most strict route but see no reason why it can't be more than 23. 

Are you using it as client or server?

**Comment by mrdg** [comment]
I'm using only the message package for encoding / decoding  at the moment actually.
