### ISSUE TITLE
why is there a dependency on websocket?

### ISSUE THREAD

**Issue by jcw** [surge/surgemq#5]
As the subject says ... I saw in the godoc dependency graph that SurgeMQ pulls in gorilla/websocket (see service/sendrecv.go) - and was curious as to why this is needed?

Great project btw - impressively well done, IMO.
-jcw

**Comment by zhenjl** [comment]
It's because I had the ambition of building websocket support but haven't gotten to it. I will remove it for now.

**Comment by jcw** [comment]
Ah, clear... thx.
